# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_custom_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='img_path',
        ),
        migrations.AddField(
            model_name='book',
            name='book_image',
            field=models.ImageField(default='book_images/None/no-img.jpg', upload_to='book_images/'),
        ),
    ]
