# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20180626_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.ImageField(default='meida/book_images/None/no-img.jpg', upload_to='media/book_images/'),
        ),
    ]
